services:
  mysql:
    image: mysql:8.0
    container_name: admin-generico-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=admin_generico
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - admin-generico-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin-generico-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_password
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - mysql
    networks:
      - admin-generico-network

volumes:
  mysql_data:

networks:
  admin-generico-network:
    driver: bridge